[package]
name = "trin-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt="0.3.25"
trin-core = { path = "../trin-core" }
jsonrpc = "0.12.0"
serde_json = { version = "1.0.68", features = ["raw_value"] }
serde = "1.0.117"
thiserror = "1.0.29"

[[bin]]
name="trin-cli"
path="src/main.rs"
